version: "3"

services:
  site1:
    build:
      context: ./site1
    restart: always
    # ports:
      # - "5001:5001"
    expose:
      - 5001
    networks:
      - app1toapp2


  site2:
    build:
      context: ./site2
    restart: always
    expose:
      - 5002
    # ports:
      # - "5002:80"
    networks:
      - app1toapp2

  nginx:
    # image: nginx
    build:
      context: ./nginx
    # volumes:
    networks:
      - app1toapp2
    ports:
      - "80:80"
    restart: always
    depends_on:
      - site1
      - site2

networks:
  app1toapp2: